language: php

php:
  - "5.5"
  - "5.4"
  - "5.3"

branches:
  only:
    - master
    - develop

before_script:
  - echo -e "[mysql]\nuser=travis\nserver=127.0.0.1\ndb=cachettest" > .cachettestrc
  - mysql -u travis -e 'drop database if exists cachettest'
  - mysql -u travis -e 'create database if not exists cachettest'
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install

